CREATE DATABASE CompanyDB;
Go

USE CompanyDB;

-- DEPARTMENT Table
CREATE TABLE DEPARTMENT (
    DNUM INT PRIMARY KEY,
    DName VARCHAR(50) NOT NULL UNIQUE,
    ManagerSSN CHAR(9) NOT NULL UNIQUE,
    HireDate DATE NOT NULL
);

-- EMPLOYEE Table
CREATE TABLE EMPLOYEE (
    SSN CHAR(9) PRIMARY KEY,
    Fname VARCHAR(30) NOT NULL,
    Lname VARCHAR(30) NOT NULL,
    BirthDate DATE NOT NULL,
    Gender CHAR(1) CHECK (Gender IN ('M', 'F')),
    DNUM INT NOT NULL,
    SupervisorSSN CHAR(9) NULL,
    FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUM),
    FOREIGN KEY (SupervisorSSN) REFERENCES EMPLOYEE(SSN)
);

-- Add the foreign key constraint for ManagerSSN after EMPLOYEE table exists
ALTER TABLE DEPARTMENT 
ADD CONSTRAINT FK_DEPARTMENT_ManagerSSN 
FOREIGN KEY (ManagerSSN) REFERENCES EMPLOYEE(SSN);

-- DEPT_LOCATIONS Table (Multivalued attribute)
CREATE TABLE DEPT_LOCATIONS (
    DNUM INT NOT NULL,
    Location VARCHAR(50) NOT NULL,
    PRIMARY KEY (DNUM, Location),
    FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUM)
);

-- PROJECT Table
CREATE TABLE PROJECT (
    PNumber INT PRIMARY KEY,
    PName VARCHAR(50) NOT NULL,
    Location VARCHAR(50),
    City VARCHAR(50),
    DNUM INT NOT NULL,
    FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUM)
);

-- WORKS_ON Table (Many-to-Many)
CREATE TABLE WORKS_ON (
    SSN CHAR(9) NOT NULL,
    PNumber INT NOT NULL,
    WorkingHours DECIMAL(5,2) NOT NULL, -- DECIMAL(5,2) = fixed-point, accurate for hours with two decimal places (max 999.99)
    PRIMARY KEY (SSN, PNumber),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN),
    FOREIGN KEY (PNumber) REFERENCES PROJECT(PNumber)
);

-- DEPENDENT Table
CREATE TABLE DEPENDENT (
    SSN CHAR(9) NOT NULL,
    DependentName VARCHAR(30) NOT NULL,
    Gender CHAR(1) CHECK (Gender IN ('M', 'F')),
    BirthDate DATE NOT NULL,
    PRIMARY KEY (SSN, DependentName),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN)
);
